CREATE USER mccolas_qar@'192.168.%' IDENTIFIED BY 'mccolasqar.31';
CREATE USER mc_qar@'192.168.%' IDENTIFIED BY 'mcqar.31';

GRANT SELECT, SHOW VIEW
ON mc_colas_qa.*
TO mccolas_qar@'192.168.%';

FLUSH PRIVILEGES;

GRANT SELECT, SHOW VIEW
ON mcqa.*
TO mc_qar@'192.168.%';

FLUSH PRIVILEGES;
