#!/bin/sh

USER=appuser # User con el que quiero correr el servicio
SERVICE_NAME=SMPPAdapterTelintelCorto # Nombre del servicio
PATH_TO_SCRIPT=/appuser/SMPPAdapterTelintelCorto # Path absoluto del java
SCRIPT=SMPPAdapterTelintelCorto.jar # Nombre del java
PID_PATH_NAME=/tmp/$SERVICE_NAME.pid # Path del pid del proceso
EXECUTE_OPTIONS="nohup java -Djava.net.preferIPv4Stack=true -Djava.util.logging.config.file=conf/logging.properties -jar -Xmx128m" # Opciones de ejecucion del script

case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            su -l $USER -c "cd $PATH_TO_SCRIPT;$EXECUTE_OPTIONS $SCRIPT & echo \$! > $PID_PATH_NAME"
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
            su -l $USER -c "cd $PATH_TO_SCRIPT;$EXECUTE_OPTIONS $SCRIPT & echo \$! > $PID_PATH_NAME"
            echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac
